export const usersData = [
  {
    id: 1,
    first_name: "Helaine",
    last_name: "Sivill",
    email: "hsivill0@xinhuanet.com",
    gender: "Female",
    address: "47 Clemons Junction",
    plans: "Yellow",
  },
  {
    id: 2,
    first_name: "Ginny",
    last_name: "Budge",
    email: "gbudge1@privacy.gov.au",
    gender: "Female",
    address: "2307 Ruskin Point",
    plans: "Aquamarine",
  },
  {
    id: 3,
    first_name: "Melloney",
    last_name: "Ohlsen",
    email: "mohlsen2@amazonaws.com",
    gender: "Female",
    address: "3 Victoria Crossing",
    plans: "Violet",
  },
  {
    id: 4,
    first_name: "Carmita",
    last_name: "Mulcahy",
    email: "cmulcahy3@unblog.fr",
    gender: "Female",
    address: "43 Schiller Circle",
    plans: "Turquoise",
  },
  {
    id: 5,
    first_name: "Padgett",
    last_name: "Pionter",
    email: "ppionter4@rambler.ru",
    gender: "Male",
    address: "1135 Mifflin Hill",
    plans: "Turquoise",
  },
  {
    id: 6,
    first_name: "Janessa",
    last_name: "Suttie",
    email: "jsuttie5@latimes.com",
    gender: "Female",
    address: "68167 Miller Point",
    plans: "Fuscia",
  },
  {
    id: 7,
    first_name: "Cassandre",
    last_name: "Meconi",
    email: "cmeconi6@prnewswire.com",
    gender: "Female",
    address: "7 Erie Street",
    plans: "Turquoise",
  },
  {
    id: 8,
    first_name: "Chilton",
    last_name: "Bamlett",
    email: "cbamlett7@privacy.gov.au",
    gender: "Male",
    address: "62906 Holy Cross Avenue",
    plans: "Maroon",
  },
  {
    id: 9,
    first_name: "Sheila-kathryn",
    last_name: "Ellsworthe",
    email: "sellsworthe8@indiatimes.com",
    gender: "Female",
    address: "27 Cherokee Drive",
    plans: "Crimson",
  },
  {
    id: 10,
    first_name: "Carolyne",
    last_name: "Payne",
    email: "cpayne9@stanford.edu",
    gender: "Female",
    address: "24 Crownhardt Alley",
    plans: "Indigo",
  },
  {
    id: 11,
    first_name: "Cristine",
    last_name: "Winnett",
    email: "cwinnetta@dell.com",
    gender: "Female",
    address: "8551 Hooker Court",
    plans: "Mauv",
  },
  {
    id: 12,
    first_name: "Ayn",
    last_name: "Holywell",
    email: "aholywellb@gmpg.org",
    gender: "Female",
    address: "3 Anniversary Lane",
    plans: "Goldenrod",
  },
  {
    id: 13,
    first_name: "Terrance",
    last_name: "Grut",
    email: "tgrutc@webnode.com",
    gender: "Male",
    address: "3791 Pennsylvania Circle",
    plans: "Turquoise",
  },
  {
    id: 14,
    first_name: "Clay",
    last_name: "Gantlett",
    email: "cgantlettd@reverbnation.com",
    gender: "Male",
    address: "7382 3rd Lane",
    plans: "Teal",
  },
  {
    id: 15,
    first_name: "Danna",
    last_name: "Ellse",
    email: "dellsee@drupal.org",
    gender: "Female",
    address: "95 Lakewood Lane",
    plans: "Turquoise",
  },
  {
    id: 16,
    first_name: "Jacki",
    last_name: "Antonignetti",
    email: "jantonignettif@ocn.ne.jp",
    gender: "Female",
    address: "2476 Pearson Center",
    plans: "Green",
  },
  {
    id: 17,
    first_name: "Peterus",
    last_name: "Reightley",
    email: "preightleyg@umn.edu",
    gender: "Male",
    address: "1192 Debs Junction",
    plans: "Turquoise",
  },
  {
    id: 18,
    first_name: "Pedro",
    last_name: "Orehead",
    email: "poreheadh@cyberchimps.com",
    gender: "Male",
    address: "86016 Nelson Center",
    plans: "Fuscia",
  },
  {
    id: 19,
    first_name: "Ivette",
    last_name: "Erasmus",
    email: "ierasmusi@cpanel.net",
    gender: "Female",
    address: "82 Raven Avenue",
    plans: "Crimson",
  },
  {
    id: 20,
    first_name: "Georgette",
    last_name: "Coch",
    email: "gcochj@seesaa.net",
    gender: "Female",
    address: "17408 Chinook Way",
    plans: "Pink",
  },
];